# Generated by Django 5.2.1 on 2025-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('regemail', models.EmailField(max_length=254, unique=True)),
                ('regpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
