# Generated by Django 5.2.1 on 2025-06-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registerbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('product_Bprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_Sprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registerbrand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registercategory')),
            ],
        ),
    ]
