# Generated by Django 5.2.3 on 2025-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
